### ISSUE TITLE
node-gyp build failed ‘NanScope’ was not declared in this scope play-server

### ISSUE THREAD

**Issue by vasudevavarun** [kaltura/play-server#274]
root@localhost:/opt/kaltura/play-server/native/node_addons/TsPreparer# node-gyp build
gyp info it worked if it ends with ok
gyp info using node-gyp@0.10.10
gyp info using node@0.10.25 | linux | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/opt/kaltura/play-server/native/node_addons/TsPreparer/build'
  CXX(target) Release/obj.target/TsPreparer/TsPreparer.o
../TsPreparer.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE GetCutDetails(Nan::NAN_METHOD_ARGS_TYPE)’:
../TsPreparer.cc:80:11: error: ‘NanScope’ was not declared in this scope
  NanScope();
           ^
../TsPreparer.cc:82:6: error: ‘args’ was not declared in this scope
  if (args.Length() < 4) 
      ^
../TsPreparer.cc:84:59: error: ‘NanThrowTypeError’ was not declared in this scope
   return NanThrowTypeError("Function requires 4 arguments");
                                                           ^
../TsPreparer.cc:84:59: error: return-statement with a value, in function returning 'void' [-fpermissive]
../TsPreparer.cc:88:7: error: ‘args’ was not declared in this scope
  if (!args[1]->IsString())
       ^
../TsPreparer.cc:90:57: error: ‘NanThrowTypeError’ was not declared in this scope
   return NanThrowTypeError("Argument 2 must be a string");
                                                         ^
../TsPreparer.cc:90:57: error: return-statement with a value, in function returning 'void' [-fpermissive]
../TsPreparer.cc:93:37: error: ‘args’ was not declared in this scope
  v8::String::Utf8Value framesBuffer(args[1]);
                                     ^
../TsPreparer.cc:98:57: error: ‘NanThrowTypeError’ was not declared in this scope
   return NanThrowTypeError("Argument 3 must be a number");
                                                         ^
../TsPreparer.cc:98:57: error: return-statement with a value, in function returning 'void' [-fpermissive]
../TsPreparer.cc:104:58: error: ‘NanThrowTypeError’ was not declared in this scope
   return NanThrowTypeError("Argument 4 must be a boolean");
                                                          ^
../TsPreparer.cc:104:58: error: return-statement with a value, in function returning 'void' [-fpermissive]
../TsPreparer.cc:112:77: error: ‘NanThrowTypeError’ was not declared in this scope
   return NanThrowTypeError("Argument 1 must be a non-empty array of buffers");
                                                                             ^
../TsPreparer.cc:112:77: error: return-statement with a value, in function returning 'void' [-fpermissive]
../TsPreparer.cc:132:55: error: ‘NanThrowError’ was not declared in this scope
   return NanThrowError("Failed to get the cut details");
                                                       ^
../TsPreparer.cc:132:55: error: return-statement with a value, in function returning 'void' [-fpermissive]
../TsPreparer.cc:139:51: error: ‘NanNewBufferHandle’ was not declared in this scope
   sizeof(*original_frames) * original_frames_count);
                                                   ^
../TsPreparer.cc:143:14: error: ‘NanNew’ was not declared in this scope
  result->Set(NanNew<String>("leftPos"),    Number::New(bounding_iframes.left_iframe_pos));
              ^
../TsPreparer.cc:143:27: error: expected primary-expression before ‘>’ token
  result->Set(NanNew<String>("leftPos"),    Number::New(bounding_iframes.left_iframe_pos));
                           ^
../TsPreparer.cc:144:27: error: expected primary-expression before ‘>’ token
  result->Set(NanNew<String>("leftOffset"),   Number::New(bounding_iframes.left_iframe_offset));
                           ^
../TsPreparer.cc:145:27: error: expected primary-expression before ‘>’ token
  result->Set(NanNew<String>("rightPos"),   Number::New(bounding_iframes.right_iframe_pos));
                           ^
../TsPreparer.cc:146:27: error: expected primary-expression before ‘>’ token
  result->Set(NanNew<String>("rightOffset"),   Number::New(bounding_iframes.right_iframe_offset));
                           ^
../TsPreparer.cc:147:27: error: expected primary-expression before ‘>’ token
  result->Set(NanNew<String>("originalFrames"),  originalFramesBuffer);
                           ^
../TsPreparer.cc:149:23: error: ‘NanReturnValue’ was not declared in this scope
  NanReturnValue(result);
                       ^
../TsPreparer.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE FindLastPatPmtPackets(Nan::NAN_METHOD_ARGS_TYPE)’:
../TsPreparer.cc:163:11: error: ‘NanScope’ was not declared in this scope
  NanScope();
           ^
../TsPreparer.cc:165:6: error: ‘args’ was not declared in this scope
  if (args.Length() < 1) 
      ^
../TsPreparer.cc:167:58: error: ‘NanThrowTypeError’ was not declared in this scope
   return NanThrowTypeError("Function requires 1 argument");
                                                          ^
../TsPreparer.cc:167:58: error: return-statement with a value, in function returning 'void' [-fpermissive]
../TsPreparer.cc:171:7: error: ‘args’ was not declared in this scope
  if (!args[0]->IsObject() || !Buffer::HasInstance(args[0]))
       ^
../TsPreparer.cc:173:57: error: ‘NanThrowTypeError’ was not declared in this scope
   return NanThrowTypeError("Argument 1 must be a buffer");
                                                         ^
../TsPreparer.cc:173:57: error: return-statement with a value, in function returning 'void' [-fpermissive]
../TsPreparer.cc:176:31: error: ‘args’ was not declared in this scope
  Local<Object> bufferObject = args[0]->ToObject();
                               ^
../TsPreparer.cc:188:17: error: ‘NanReturnNull’ was not declared in this scope
   NanReturnNull();
                 ^
../TsPreparer.cc:192:14: error: ‘NanNew’ was not declared in this scope
  result->Set(NanNew<String>("pat"), Number::New(lastPatPacket - sourceBuffer));
              ^
../TsPreparer.cc:192:27: error: expected primary-expression before ‘>’ token
  result->Set(NanNew<String>("pat"), Number::New(lastPatPacket - sourceBuffer));
                           ^
../TsPreparer.cc:193:27: error: expected primary-expression before ‘>’ token
  result->Set(NanNew<String>("pmt"), Number::New(lastPmtPacket - sourceBuffer));
                           ^
../TsPreparer.cc:195:23: error: ‘NanReturnValue’ was not declared in this scope
  NanReturnValue(result);
                       ^
../TsPreparer.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE PrepareTs(Nan::NAN_METHOD_ARGS_TYPE)’:
../TsPreparer.cc:214:11: error: ‘NanScope’ was not declared in this scope
  NanScope();
           ^
../TsPreparer.cc:216:6: error: ‘args’ was not declared in this scope
  if (args.Length() < 1) 
      ^
../TsPreparer.cc:218:60: error: ‘NanThrowTypeError’ was not declared in this scope
   return NanThrowTypeError("Function requires one argument");
                                                            ^
../TsPreparer.cc:218:60: error: return-statement with a value, in function returning 'void' [-fpermissive]
../TsPreparer.cc:222:7: error: ‘args’ was not declared in this scope
  if (!args[0]->IsArray())
       ^
../TsPreparer.cc:224:57: error: ‘NanThrowTypeError’ was not declared in this scope
   return NanThrowTypeError("Argument 1 must be an array");
                                                         ^
../TsPreparer.cc:224:57: error: return-statement with a value, in function returning 'void' [-fpermissive]
../TsPreparer.cc:227:28: error: ‘args’ was not declared in this scope
  Local<Array> partsArray = args[0].As<Array>();
                            ^
../TsPreparer.cc:227:44: error: expected primary-expression before ‘>’ token
  Local<Array> partsArray = args[0].As<Array>();
                                            ^
../TsPreparer.cc:227:46: error: expected primary-expression before ‘)’ token
  Local<Array> partsArray = args[0].As<Array>();
                                              ^
../TsPreparer.cc:231:57: error: ‘NanThrowTypeError’ was not declared in this scope
   return NanThrowTypeError("Parts array cannot be empty");
                                                         ^
../TsPreparer.cc:231:57: error: return-statement with a value, in function returning 'void' [-fpermissive]
../TsPreparer.cc:237:56: error: ‘NanThrowError’ was not declared in this scope
   return NanThrowError("Failed to allocate parts array");
                                                        ^
../TsPreparer.cc:237:56: error: return-statement with a value, in function returning 'void' [-fpermissive]
../TsPreparer.cc:247:63: error: ‘NanThrowTypeError’ was not declared in this scope
    return NanThrowTypeError("Parts array must contain objects");
                                                               ^
../TsPreparer.cc:247:63: error: return-statement with a value, in function returning 'void' [-fpermissive]
../TsPreparer.cc:253:41: error: ‘NanNew’ was not declared in this scope
   Local<Value> buffers = curObject->Get(NanNew<String>("buffers"));
                                         ^
../TsPreparer.cc:253:54: error: expected primary-expression before ‘>’ token
   Local<Value> buffers = curObject->Get(NanNew<String>("buffers"));
                                                      ^
../TsPreparer.cc:258:82: error: ‘NanThrowTypeError’ was not declared in this scope
    return NanThrowTypeError("Each part must contain a non-empty array of buffers");
                                                                                  ^
../TsPreparer.cc:258:82: error: return-statement with a value, in function returning 'void' [-fpermissive]
../TsPreparer.cc:262:53: error: expected primary-expression before ‘>’ token
   Local<Value> frames = curObject->Get(NanNew<String>("frames"));
                                                     ^
../TsPreparer.cc:266:69: error: ‘NanThrowTypeError’ was not declared in this scope
    return NanThrowTypeError("Each part must contain a frames buffer");
                                                                     ^
../TsPreparer.cc:266:69: error: return-statement with a value, in function returning 'void' [-fpermissive]
../TsPreparer.cc:275:61: error: expected primary-expression before ‘>’ token
   Local<Value> framesPosShift = curObject->Get(NanNew<String>("framesPosShift"));
                                                             ^
../TsPreparer.cc:279:77: error: ‘NanThrowTypeError’ was not declared in this scope
    return NanThrowTypeError("Each part must contain a framesPosShift number");
                                                                             ^
../TsPreparer.cc:279:77: error: return-statement with a value, in function returning 'void' [-fpermissive]
../TsPreparer.cc:285:52: error: expected primary-expression before ‘>’ token
   Local<Value> flags = curObject->Get(NanNew<String>("flags"));
                                                    ^
../TsPreparer.cc:289:68: error: ‘NanThrowTypeError’ was not declared in this scope
    return NanThrowTypeError("Each part must contain a flags number");
                                                                    ^
../TsPreparer.cc:289:68: error: return-statement with a value, in function returning 'void' [-fpermissive]
../TsPreparer.cc:310:51: error: ‘NanThrowError’ was not declared in this scope
   return NanThrowError("Failed to prepare TS data");
                                                   ^
../TsPreparer.cc:310:51: error: return-statement with a value, in function returning 'void' [-fpermissive]
../TsPreparer.cc:313:104: error: ‘NanNewBufferHandle’ was not declared in this scope
  Local<Object> metadataBuffer = NanNewBufferHandle((char*)outputMetadata.data, outputMetadata.write_pos);
                                                                                                        ^
../TsPreparer.cc:322:14: error: ‘NanNew’ was not declared in this scope
  result->Set(NanNew<String>("metadata"), metadataBuffer);
              ^
../TsPreparer.cc:322:27: error: expected primary-expression before ‘>’ token
  result->Set(NanNew<String>("metadata"), metadataBuffer);
                           ^
../TsPreparer.cc:323:27: error: expected primary-expression before ‘>’ token
  result->Set(NanNew<String>("header"), headerBuffer);
                           ^
../TsPreparer.cc:324:27: error: expected primary-expression before ‘>’ token
  result->Set(NanNew<String>("data"), dataBuffer);
                           ^
../TsPreparer.cc:326:23: error: ‘NanReturnValue’ was not declared in this scope
  NanReturnValue(result);
                       ^
../TsPreparer.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE ParseFramesInfo(Nan::NAN_METHOD_ARGS_TYPE)’:
../TsPreparer.cc:339:11: error: ‘NanScope’ was not declared in this scope
  NanScope();
           ^
../TsPreparer.cc:341:6: error: ‘args’ was not declared in this scope
  if (args.Length() < 2) 
      ^
../TsPreparer.cc:343:59: error: ‘NanThrowTypeError’ was not declared in this scope
   return NanThrowTypeError("Function requires 2 arguments");
                                                           ^
../TsPreparer.cc:343:59: error: return-statement with a value, in function returning 'void' [-fpermissive]
../TsPreparer.cc:347:7: error: ‘args’ was not declared in this scope
  if (!args[1]->IsString())
       ^
../TsPreparer.cc:349:57: error: ‘NanThrowTypeError’ was not declared in this scope
   return NanThrowTypeError("Argument 2 must be a string");
                                                         ^
../TsPreparer.cc:349:57: error: return-statement with a value, in function returning 'void' [-fpermissive]
../TsPreparer.cc:352:37: error: ‘args’ was not declared in this scope
  v8::String::Utf8Value framesBuffer(args[1]);
                                     ^
../TsPreparer.cc:358:77: error: ‘NanThrowTypeError’ was not declared in this scope
   return NanThrowTypeError("Argument 1 must be a non-empty array of buffers");
                                                                             ^
../TsPreparer.cc:358:77: error: return-statement with a value, in function returning 'void' [-fpermissive]
../TsPreparer.cc:378:53: error: ‘NanThrowError’ was not declared in this scope
   return NanThrowError("Failed to parse frames info");
                                                     ^
../TsPreparer.cc:378:53: error: return-statement with a value, in function returning 'void' [-fpermissive]
../TsPreparer.cc:382:107: error: ‘NanNewBufferHandle’ was not declared in this scope
  Local<Object> result = NanNewBufferHandle((char*)source_frames, sizeof(frame_info_t) * source_frame_count);
                                                                                                           ^
../TsPreparer.cc:386:23: error: ‘NanReturnValue’ was not declared in this scope
  NanReturnValue(result);
                       ^
../TsPreparer.cc: In function ‘void init(v8::Handle<v8::Object>)’:
../TsPreparer.cc:391:15: error: ‘NanNew’ was not declared in this scope
  exports->Set(NanNew<String>("getCutDetails"),    FunctionTemplate::New(GetCutDetails)->GetFunction());
               ^
../TsPreparer.cc:391:28: error: expected primary-expression before ‘>’ token
  exports->Set(NanNew<String>("getCutDetails"),    FunctionTemplate::New(GetCutDetails)->GetFunction());
                            ^
../TsPreparer.cc:391:86: error: invalid conversion from ‘Nan::NAN_METHOD_RETURN_TYPE (*)(Nan::NAN_METHOD_ARGS_TYPE) {aka void (*)(const Nan::FunctionCallbackInfo<v8::Value>&)}’ to ‘v8::InvocationCallback {aka v8::Handle<v8::Value> (*)(const v8::Arguments&)}’ [-fpermissive]
  exports->Set(NanNew<String>("getCutDetails"),    FunctionTemplate::New(GetCutDetails)->GetFunction());
                                                                                      ^
In file included from /usr/include/nodejs/src/node.h:62:0,
                 from ../../../../node_modules/nan/nan.h:47,
                 from ../TsPreparer.cc:2:
/usr/include/nodejs/deps/v8/include/v8.h:2255:34: error:   initializing argument 1 of ‘static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::InvocationCallback, v8::Handle<v8::Value>, v8::Handle<v8::Signature>)’ [-fpermissive]
   static Local<FunctionTemplate> New(
                                  ^
../TsPreparer.cc:392:28: error: expected primary-expression before ‘>’ token
  exports->Set(NanNew<String>("findLastPatPmtPackets"),  FunctionTemplate::New(FindLastPatPmtPackets)->GetFunction());
                            ^
../TsPreparer.cc:392:100: error: invalid conversion from ‘Nan::NAN_METHOD_RETURN_TYPE (*)(Nan::NAN_METHOD_ARGS_TYPE) {aka void (*)(const Nan::FunctionCallbackInfo<v8::Value>&)}’ to ‘v8::InvocationCallback {aka v8::Handle<v8::Value> (*)(const v8::Arguments&)}’ [-fpermissive]
  exports->Set(NanNew<String>("findLastPatPmtPackets"),  FunctionTemplate::New(FindLastPatPmtPackets)->GetFunction());
                                                                                                    ^
In file included from /usr/include/nodejs/src/node.h:62:0,
                 from ../../../../node_modules/nan/nan.h:47,
                 from ../TsPreparer.cc:2:
/usr/include/nodejs/deps/v8/include/v8.h:2255:34: error:   initializing argument 1 of ‘static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::InvocationCallback, v8::Handle<v8::Value>, v8::Handle<v8::Signature>)’ [-fpermissive]
   static Local<FunctionTemplate> New(
                                  ^
../TsPreparer.cc:393:28: error: expected primary-expression before ‘>’ token
  exports->Set(NanNew<String>("prepareTs"),     FunctionTemplate::New(PrepareTs)->GetFunction());
                            ^
../TsPreparer.cc:393:79: error: invalid conversion from ‘Nan::NAN_METHOD_RETURN_TYPE (*)(Nan::NAN_METHOD_ARGS_TYPE) {aka void (*)(const Nan::FunctionCallbackInfo<v8::Value>&)}’ to ‘v8::InvocationCallback {aka v8::Handle<v8::Value> (*)(const v8::Arguments&)}’ [-fpermissive]
  exports->Set(NanNew<String>("prepareTs"),     FunctionTemplate::New(PrepareTs)->GetFunction());
                                                                               ^
In file included from /usr/include/nodejs/src/node.h:62:0,
                 from ../../../../node_modules/nan/nan.h:47,
                 from ../TsPreparer.cc:2:
/usr/include/nodejs/deps/v8/include/v8.h:2255:34: error:   initializing argument 1 of ‘static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::InvocationCallback, v8::Handle<v8::Value>, v8::Handle<v8::Signature>)’ [-fpermissive]
   static Local<FunctionTemplate> New(
                                  ^
../TsPreparer.cc:394:28: error: expected primary-expression before ‘>’ token
  exports->Set(NanNew<String>("parseFramesInfo"),   FunctionTemplate::New(ParseFramesInfo)->GetFunction());
                            ^
../TsPreparer.cc:394:89: error: invalid conversion from ‘Nan::NAN_METHOD_RETURN_TYPE (*)(Nan::NAN_METHOD_ARGS_TYPE) {aka void (*)(const Nan::FunctionCallbackInfo<v8::Value>&)}’ to ‘v8::InvocationCallback {aka v8::Handle<v8::Value> (*)(const v8::Arguments&)}’ [-fpermissive]
  exports->Set(NanNew<String>("parseFramesInfo"),   FunctionTemplate::New(ParseFramesInfo)->GetFunction());
                                                                                         ^
In file included from /usr/include/nodejs/src/node.h:62:0,
                 from ../../../../node_modules/nan/nan.h:47,
                 from ../TsPreparer.cc:2:
/usr/include/nodejs/deps/v8/include/v8.h:2255:34: error:   initializing argument 1 of ‘static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::InvocationCallback, v8::Handle<v8::Value>, v8::Handle<v8::Signature>)’ [-fpermissive]
   static Local<FunctionTemplate> New(
                                  ^
make: *** [Release/obj.target/TsPreparer/TsPreparer.o] Error 1
make: Leaving directory `/opt/kaltura/play-server/native/node_addons/TsPreparer/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.19.0-25-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "build"
gyp ERR! cwd /opt/kaltura/play-server/native/node_addons/TsPreparer
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok

**Comment by kaltura-hooks** [comment]
Hi @vasudevavarun,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by david-winder-kaltura** [comment]
It is seem that you are not using the 'nan_Adaptor.h' . What is your nan version? node version?
